name: Android CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      buildType:
        description: "Build type"
        required: true
        default: debug
        type: choice
        options:
          - debug
          - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Debug APK
        if: ${{ github.event.inputs.buildType == 'debug' || github.event.inputs.buildType == '' }}
        run: ./gradlew assembleDebug

      - name: Build Release APK
        if: ${{ github.event.inputs.buildType == 'release' }}
        run: ./gradlew assembleRelease
